// FIFA ISO-3 → flag CDN code (ISO 3166-1 alpha-2, plus subdivisions for UK home nations).
// Covers Mundial 2026 confirmed/probable teams. Extend as new teams qualify.
export const ISO3_TO_FLAG: Record<string, string> = {
  ARG: 'ar',
  AUS: 'au',
  AUT: 'at',
  BEL: 'be',
  BIH: 'ba',
  BRA: 'br',
  CAN: 'ca',
  CHI: 'cl',
  CIV: 'ci',
  COL: 'co',
  CPV: 'cv',
  CRC: 'cr',
  CRO: 'hr',
  CUW: 'cw',
  CZE: 'cz',
  DEN: 'dk',
  ECU: 'ec',
  EGY: 'eg',
  ENG: 'gb-eng',
  ESP: 'es',
  FRA: 'fr',
  GER: 'de',
  GHA: 'gh',
  HAI: 'ht',
  HUN: 'hu',
  IRN: 'ir',
  ISL: 'is',
  ITA: 'it',
  JPN: 'jp',
  KOR: 'kr',
  KSA: 'sa',
  MAR: 'ma',
  MEX: 'mx',
  NED: 'nl',
  NGA: 'ng',
  NIR: 'gb-nir',
  NOR: 'no',
  NZL: 'nz',
  PAR: 'py',
  PER: 'pe',
  POL: 'pl',
  POR: 'pt',
  QAT: 'qa',
  ROU: 'ro',
  RSA: 'za',
  SCO: 'gb-sct',
  SEN: 'sn',
  SRB: 'rs',
  SUI: 'ch',
  SWE: 'se',
  TUN: 'tn',
  TUR: 'tr',
  UAE: 'ae',
  UKR: 'ua',
  URU: 'uy',
  USA: 'us',
  VEN: 've',
  WAL: 'gb-wls',
}

export function flagCode(iso3: string | null | undefined): string | null {
  if (!iso3) return null
  return ISO3_TO_FLAG[iso3.toUpperCase()] ?? null
}
